using Microsoft.EntityFrameworkCore;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using APP.Extensions;
using APP.IRepository;
using APP.Services.Email;
using APP.Utils;
using AutoMapper;
using DOMAIN.Entities.Employees;
using DOMAIN.Entities.Users;
using INFRASTRUCTURE.Context;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;
using SHARED;
using EntityFrameworkQueryableExtensions = Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions;


namespace APP.Repository;

public class EmployeeRepository(ApplicationDbContext context,
    ILogger<EmployeeRepository> logger, IEmailService emailService, IMapper mapper,
    IConfiguration configuration) : IEmployeeRepository
{

public async Task<Result> OnboardEmployees(OnboardEmployeeDto employeeDtos)
{
    const int maxRetries = 3;
    
    var templatePath = Path.GetFullPath(Path.Combine("..", "APP", "Services", "Email", "Templates", "RegistrationEmail.html"));
    if (!File.Exists(templatePath))
        throw new FileNotFoundException("Email template not found", templatePath);

    var emailTemplate = await File.ReadAllTextAsync(templatePath);
    
    var tokenHandler = new JwtSecurityTokenHandler();
    var jwtKey = configuration["JwtSettings:Key"];
    var keyBytes = Encoding.UTF8.GetBytes(jwtKey);
  
    foreach (var employee in employeeDtos.EmailList)
    {
        try
        {
            // autogenerated staff number for casual employees
            var generateStaffNumber = employee.EmployeeType == EmployeeType.Casual ? GenerateStaffNumber(): "";
            employee.StaffNumber = generateStaffNumber;

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity([
                    new Claim("type", employee.EmployeeType.ToString())
                ]),
                Expires = DateTime.UtcNow.AddDays(7),
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(keyBytes), SecurityAlgorithms.HmacSha256Signature)
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);
            var jwt = tokenHandler.WriteToken(token);
            
            var verificationLink = employee.EmployeeType == EmployeeType.Casual
                ? $"http://164.90.142.68:3005/onboarding/0?token={jwt}"
                : $"http://164.90.142.68:3005/onboarding/1?token={jwt}";
            
            var emailBody = emailTemplate
                .Replace("{Email}", employee.Email)
                .Replace("{VerificationLink}", verificationLink);

            // Send email with retry
            var attempts = 0;
            var sent = false;

            while (attempts < maxRetries && !sent)
            {
                try 
                {
                    emailService.SendMail(employee.Email, "Welcome to the team", emailBody, []);
                    logger.LogInformation($"Email sent to {employee.Email}");
                    sent = true;
                }
                catch (Exception ex)
                {
                    attempts++;
                    logger.LogWarning($"Failed attempt {attempts} for {employee.Email}: {ex.Message}");

                    if (attempts == maxRetries)
                        logger.LogError($"Giving up on {employee.Email} after {maxRetries} attempts.");
                }
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, $"Error onboarding {employee.Email}");
        }
    }

    return Result.Success("Bulk onboarding completed.");
}

    private static string GenerateStaffNumber()
    {
        const string prefix = "EMP";
        var year = DateTime.UtcNow.Year.ToString();
        var random = new Random();
        var uniqueNumber = random.Next(1000, 9999); 

        return $"{prefix}-{year}-{uniqueNumber}";
    }
    public async Task<Result<Guid?>> CreateEmployee(CreateEmployeeRequest request, Guid userId)
    {
        var employee = mapper.Map<Employee>(request);
        employee.CreatedById = userId;
        employee.CreatedAt = DateTime.UtcNow;
        context.Employees.Add(employee);
        await context.SaveChangesAsync();

        return employee.Id;
    }

    public async Task<Result> CreateEmployeeUser(EmployeeDto employeeDto, UserDto userDto, Guid userId)
    {
        var employee = await context.Employees.FirstOrDefaultAsync(e => e.Id == employeeDto.Id && e.LastDeletedById == null);

        if (employee == null)
        {
            return Error.NotFound("Employee.NotFound",$"Employee with email {employeeDto.Email} not found");
        }
        
        var newUser = mapper.Map<User>(employeeDto);
        newUser.CreatedById = userId;
        newUser.CreatedAt = DateTime.UtcNow;
        
        context.Users.Add(newUser);
        await context.SaveChangesAsync();
        
        var templatePath = Path.GetFullPath(Path.Combine("..", "APP", "Services", "Email", "Templates", "PasswordSetup.html"));
        if (!File.Exists(templatePath))
            throw new FileNotFoundException("Email template not found", templatePath);

        var emailTemplate = await File.ReadAllTextAsync(templatePath);
            
        var tokenHandler = new JwtSecurityTokenHandler();
        var jwtKey = configuration["JwtSettings:Key"];
        var keyBytes = Encoding.UTF8.GetBytes(jwtKey);
        
         try
        {
            const int maxRetries = 3;
            
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity([
                    new Claim("type", employee.Id.ToString())
                ]),
                Expires = DateTime.UtcNow.AddDays(7),
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(keyBytes), SecurityAlgorithms.HmacSha256Signature)
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);
            var jwt = tokenHandler.WriteToken(token);

            var verificationLink = $"http://164.90.142.68:3005/reset-password?email={employee.Email}/{jwt}";
            
            var emailBody = emailTemplate
                .Replace("{Email}", employee.Email)
                .Replace("{VerificationLink}", verificationLink);

            // Send email with retry
            var attempts = 0;
            var sent = false;

            while (attempts < maxRetries && !sent)
            {
                try 
                {
                    emailService.SendMail(employee.Email, "Password Setup", emailBody, []);
                    logger.LogInformation($"Email sent to {employee.Email}");
                    sent = true;
                }
                catch (Exception ex)
                {
                    attempts++;
                    logger.LogWarning($"Failed attempt {attempts} for {employee.Email}: {ex.Message}");

                    if (attempts == maxRetries)
                        logger.LogError($"Giving up on {employee.Email} after {maxRetries} attempts.");
                }
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, $"Error onboarding {employee.Email}");
        }
         
        return Result.Success(newUser.Id);
    }

    public async Task<Result<EmployeeDto>> GetEmployee(Guid id)
    {
        var employee = await context.Employees
            .Include(e=> e.Department)
            .FirstOrDefaultAsync(e => e.Id == id && e.LastDeletedById == null);

        if (employee == null)
        {
            return Error.NotFound("Employee.NotFound", "Employee not found");
        }

        var employeeDto = mapper.Map<EmployeeDto>(employee);
        return Result.Success(employeeDto);
    }
    
    public async Task<Result<Paginateable<IEnumerable<EmployeeDto>>>> GetEmployees(int page, int pageSize,
        string searchQuery, string designation, string department)
    {
        var query = context.Employees
            .Include(e => e.Department)
            .Include(e => e.Designation)
            .Where(e => e.LastDeletedById == null)
            .AsQueryable();
        
        if (!string.IsNullOrWhiteSpace(searchQuery))
        {
            query = query.WhereSearch(searchQuery, q => q.Email);
        }

        if (!string.IsNullOrWhiteSpace(designation))
        {
            query = query.WhereSearch(designation, q => q.Designation.Name);
        }

        if (!string.IsNullOrWhiteSpace(department))
        {
            query = query.WhereSearch(department, q => q.Department.Name);
        }

        return await PaginationHelper.GetPaginatedResultAsync(
            query, 
            page, 
            pageSize, 
            mapper.Map<EmployeeDto>
        );
    }

    public async Task<Result> UpdateEmployee(Guid id, CreateEmployeeRequest request, Guid userId)
    {
        var employee = await context.Employees
            .FirstOrDefaultAsync(e => e.Id == id && e.LastDeletedById == null);

        if (employee == null)
        {
            return Error.NotFound("Employee.NotFound", "Employee not found");
        }

        mapper.Map(request, employee);
        employee.UpdatedAt = DateTime.UtcNow;
        employee.LastUpdatedById = userId;
        context.Employees.Update(employee);
        await context.SaveChangesAsync();

        return Result.Success();
    }

public async Task<Result> AssignEmployee(Guid id, AssignEmployeeDto employeeDto, Guid userId)
{
    // Step 1: Retrieve employee with department and designation loaded
    var employee = await context.Employees
        .Include(e => e.Department)
        .Include(e => e.Designation)
        .FirstOrDefaultAsync(e => e.Id == id && e.LastDeletedById == null);

    if (employee == null)
    {
        return Error.NotFound("Employee.NotFound", "Employee not found");
    }
    
    mapper.Map(employeeDto, employee);
    employee.DepartmentId = employeeDto.DepartmentId;
    employee.DesignationId = employeeDto.DesignationId;
    employee.UpdatedAt = DateTime.UtcNow;
    employee.LastUpdatedById = userId;

    context.Employees.Update(employee);
    await context.SaveChangesAsync();
    
    await context.Entry(employee).Reference(e => e.Department).LoadAsync();
    await context.Entry(employee).Reference(e => e.Designation).LoadAsync();

    // Step 4: Prepare and send the email
    var templatePath = Path.Combine("..","APP", "Services", "Email", "Templates", "EmployeeAcceptance.html");
    if (!File.Exists(templatePath))
        throw new FileNotFoundException("Email template not found", templatePath);

    var emailTemplate = await File.ReadAllTextAsync(templatePath);

    var body = emailTemplate
        .Replace("{Name}", employee.FullName)
        .Replace("{Email}", employee.Email)
        .Replace("{DesignationName}", employee.Designation?.Name)
        .Replace("{DepartmentName}", employee.Department?.Name);

    const int maxRetries = 3;
    var attempts = 0;
    var sent = false;

    while (attempts < maxRetries && !sent)
    {
        try
        {
            emailService.SendMail(employee.Email, "Welcome to the Company", body, []);
            logger.LogInformation($"Email sent to {employee.Email}");
            sent = true;
        }
        catch (Exception ex)
        {
            attempts++;
            logger.LogWarning($"Failed attempt {attempts} for {employee.Email}: {ex.Message}");

            if (attempts == maxRetries)
                logger.LogError($"Giving up on {employee.Email} after {maxRetries} attempts.");
        }
    }

    return Result.Success();
}

    public async Task<Result> DeleteEmployee(Guid id, Guid userId)
    {
        var employee = await context.Employees.FirstOrDefaultAsync(e => e.Id == id && e.LastDeletedById == null);

        if (employee == null)
        {
            return Error.NotFound("Employee.NotFound", "Employee not found");
        }
        employee.DeletedAt = DateTime.UtcNow;
        employee.LastDeletedById = userId;
        
        context.Employees.Update(employee);
        await context.SaveChangesAsync();
        return Result.Success();
    }
}
