services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: oryx-api
    ports:
      - "8080:5001"
    environment:
      - connectionString=Host=postgres_db;Port=5432;Username=${DB_USERNAME};Password=${DB_PASSWORD};Database=${DB_DATABASE}
      - redisConnectionString=redis:6379,abortConnect=false
      - RUN_TEST_SEEDS=ON
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=entrance@10
      - MINIO_PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
      - RABBITMQ_HOST=164.90.142.68
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=MvK6o4yR1CUXarZ
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
    volumes:
      - ./https:/https:ro
    networks:
      - sail
    container_name: oryx_api

networks:
  sail:
    external: true
  shared:
    driver: bridge
