services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: oryxapi
    ports:
      - "8082:5001"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - oryxDbConnectionString=Host=postgres_db;Port=5432;Username=${DB_USERNAME};Password=${DB_PASSWORD};Database=${DB_DATABASE}
      - redisConnectionString=redis:6379,abortConnect=false
      - RUN_TEST_SEEDS=ON
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=${ACCESS_KEY}
      - MINIO_SECRET_KEY=${SECRET_KEY}
      - MINIO_PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
    volumes:
      - ~/.aspnet/https:/https:ro
      - .:/app
    networks:
      - sail
    container_name: oryx_api

networks:
  sail:
    external: true  # This indicates the network is already created and shared
  shared:
    driver: bridge
