namespace DOMAIN.Entities.Countries;

public static class CountryUtils
{
    private static readonly List<CountryDto> Countries =
    [
        new CountryDto { Name = "Afghanistan", Nationality = "Afghan", Code = "AF" },
        new CountryDto { Name = "Albania", Nationality = "Albanian", Code = "AL" },
        new CountryDto { Name = "Algeria", Nationality = "Algerian", Code = "DZ" },
        new CountryDto { Name = "Andorra", Nationality = "Andorran", Code = "AD" },
        new CountryDto { Name = "Angola", Nationality = "Angolan", Code = "AO" },
        new CountryDto { Name = "Antigua and Barbuda", Nationality = "Antiguan/Barbudan", Code = "AG" },
        new CountryDto { Name = "Argentina", Nationality = "Argentine", Code = "AR" },
        new CountryDto { Name = "Armenia", Nationality = "Armenian", Code = "AM" },
        new CountryDto { Name = "Australia", Nationality = "Australian", Code = "AU" },
        new CountryDto { Name = "Austria", Nationality = "Austrian", Code = "AT" },
        new CountryDto { Name = "Azerbaijan", Nationality = "Azerbaijani", Code = "AZ" },
        new CountryDto { Name = "Bahamas", Nationality = "Bahamian", Code = "BS" },
        new CountryDto { Name = "Bahrain", Nationality = "Bahraini", Code = "BH" },
        new CountryDto { Name = "Bangladesh", Nationality = "Bangladeshi", Code = "BD" },
        new CountryDto { Name = "Barbados", Nationality = "Barbadian", Code = "BB" },
        new CountryDto { Name = "Belarus", Nationality = "Belarusian", Code = "BY" },
        new CountryDto { Name = "Belgium", Nationality = "Belgian", Code = "BE" },
        new CountryDto { Name = "Belize", Nationality = "Belizean", Code = "BZ" },
        new CountryDto { Name = "Benin", Nationality = "Beninese", Code = "BJ" },
        new CountryDto { Name = "Bhutan", Nationality = "Bhutanese", Code = "BT" },
        new CountryDto { Name = "Bolivia", Nationality = "Bolivian", Code = "BO" },
        new CountryDto { Name = "Bosnia and Herzegovina", Nationality = "Bosnian/Herzegovinian", Code = "BA" },
        new CountryDto { Name = "Botswana", Nationality = "Batswana", Code = "BW" },
        new CountryDto { Name = "Brazil", Nationality = "Brazilian", Code = "BR" },
        new CountryDto { Name = "Brunei", Nationality = "Bruneian", Code = "BN" },
        new CountryDto { Name = "Bulgaria", Nationality = "Bulgarian", Code = "BG" },
        new CountryDto { Name = "Burkina Faso", Nationality = "Burkinabe", Code = "BF" },
        new CountryDto { Name = "Burundi", Nationality = "Burundian", Code = "BI" },
        new CountryDto { Name = "Cabo Verde", Nationality = "Cape Verdean", Code = "CV" },
        new CountryDto { Name = "Cambodia", Nationality = "Cambodian", Code = "KH" },
        new CountryDto { Name = "Cameroon", Nationality = "Cameroonian", Code = "CM" },
        new CountryDto { Name = "Canada", Nationality = "Canadian", Code = "CA" },
        new CountryDto { Name = "Central African Republic", Nationality = "Central African", Code = "CF" },
        new CountryDto { Name = "Chad", Nationality = "Chadian", Code = "TD" },
        new CountryDto { Name = "Chile", Nationality = "Chilean", Code = "CL" },
        new CountryDto { Name = "China", Nationality = "Chinese", Code = "CN" },
        new CountryDto { Name = "Colombia", Nationality = "Colombian", Code = "CO" },
        new CountryDto { Name = "Comoros", Nationality = "Comorian", Code = "KM" },
        new CountryDto { Name = "Congo, Democratic Republic of the", Nationality = "Congolese (DRC)", Code = "CD" },
        new CountryDto { Name = "Congo, Republic of the", Nationality = "Congolese", Code = "CG" },
        new CountryDto { Name = "Costa Rica", Nationality = "Costa Rican", Code = "CR" },
        new CountryDto { Name = "Croatia", Nationality = "Croatian", Code = "HR" },
        new CountryDto { Name = "Cuba", Nationality = "Cuban", Code = "CU" },
        new CountryDto { Name = "Cyprus", Nationality = "Cypriot", Code = "CY" },
        new CountryDto { Name = "Czech Republic", Nationality = "Czech", Code = "CZ" },
        new CountryDto { Name = "Denmark", Nationality = "Danish", Code = "DK" },
        new CountryDto { Name = "Djibouti", Nationality = "Djiboutian", Code = "DJ" },
        new CountryDto { Name = "Dominica", Nationality = "Dominican", Code = "DM" },
        new CountryDto { Name = "Dominican Republic", Nationality = "Dominican", Code = "DO" },
        new CountryDto { Name = "East Timor (Timor-Leste)", Nationality = "Timorese", Code = "TL" },
        new CountryDto { Name = "Ecuador", Nationality = "Ecuadorian", Code = "EC" },
        new CountryDto { Name = "Egypt", Nationality = "Egyptian", Code = "EG" },
        new CountryDto { Name = "El Salvador", Nationality = "Salvadoran", Code = "SV" },
        new CountryDto { Name = "Equatorial Guinea", Nationality = "Equatorial Guinean", Code = "GQ" },
        new CountryDto { Name = "Eritrea", Nationality = "Eritrean", Code = "ER" },
        new CountryDto { Name = "Estonia", Nationality = "Estonian", Code = "EE" },
        new CountryDto { Name = "Eswatini (Swaziland)", Nationality = "Swazi", Code = "SZ" },
        new CountryDto { Name = "Ethiopia", Nationality = "Ethiopian", Code = "ET" },
        new CountryDto { Name = "Fiji", Nationality = "Fijian", Code = "FJ" },
        new CountryDto { Name = "Finland", Nationality = "Finnish", Code = "FI" },
        new CountryDto { Name = "France", Nationality = "French", Code = "FR" },
        new CountryDto { Name = "Gabon", Nationality = "Gabonese", Code = "GA" },
        new CountryDto { Name = "Gambia", Nationality = "Gambian", Code = "GM" },
        new CountryDto { Name = "Georgia", Nationality = "Georgian", Code = "GE" },
        new CountryDto { Name = "Germany", Nationality = "German", Code = "DE" },
        new CountryDto { Name = "Ghana", Nationality = "Ghanaian", Code = "GH" },
        new CountryDto { Name = "Greece", Nationality = "Greek", Code = "GR" },
        new CountryDto { Name = "Grenada", Nationality = "Grenadian", Code = "GD" },
        new CountryDto { Name = "Guatemala", Nationality = "Guatemalan", Code = "GT" },
        new CountryDto { Name = "Guinea", Nationality = "Guinean", Code = "GN" },
        new CountryDto { Name = "Guinea-Bissau", Nationality = "Bissau-Guinean", Code = "GW" },
        new CountryDto { Name = "Guyana", Nationality = "Guyanese", Code = "GY" },
        new CountryDto { Name = "Haiti", Nationality = "Haitian", Code = "HT" },
        new CountryDto { Name = "Honduras", Nationality = "Honduran", Code = "HN" },
        new CountryDto { Name = "Hungary", Nationality = "Hungarian", Code = "HU" },
        new CountryDto { Name = "Iceland", Nationality = "Icelander", Code = "IS" },
        new CountryDto { Name = "India", Nationality = "Indian", Code = "IN" },
        new CountryDto { Name = "Indonesia", Nationality = "Indonesian", Code = "ID" },
        new CountryDto { Name = "Iran", Nationality = "Iranian", Code = "IR" },
        new CountryDto { Name = "Iraq", Nationality = "Iraqi", Code = "IQ" },
        new CountryDto { Name = "Ireland", Nationality = "Irish", Code = "IE" },
        new CountryDto { Name = "Israel", Nationality = "Israeli", Code = "IL" },
        new CountryDto { Name = "Italy", Nationality = "Italian", Code = "IT" },
        new CountryDto { Name = "Ivory Coast (Côte d'Ivoire)", Nationality = "Ivorian", Code = "CI" },
        new CountryDto { Name = "Jamaica", Nationality = "Jamaican", Code = "JM" },
        new CountryDto { Name = "Japan", Nationality = "Japanese", Code = "JP" },
        new CountryDto { Name = "Jordan", Nationality = "Jordanian", Code = "JO" },
        new CountryDto { Name = "Kazakhstan", Nationality = "Kazakhstani", Code = "KZ" },
        new CountryDto { Name = "Kenya", Nationality = "Kenyan", Code = "KE" },
        new CountryDto { Name = "Kiribati", Nationality = "I-Kiribati", Code = "KI" },
        new CountryDto { Name = "Korea, North", Nationality = "North Korean", Code = "KP" },
        new CountryDto { Name = "Korea, South", Nationality = "South Korean", Code = "KR" },
        new CountryDto { Name = "Kosovo", Nationality = "Kosovar", Code = "XK" },
        new CountryDto { Name = "Kuwait", Nationality = "Kuwaiti", Code = "KW" },
        new CountryDto { Name = "Kyrgyzstan", Nationality = "Kyrgyz", Code = "KG" },
        new CountryDto { Name = "Laos", Nationality = "Laotian", Code = "LA" },
        new CountryDto { Name = "Latvia", Nationality = "Latvian", Code = "LV" },
        new CountryDto { Name = "Lebanon", Nationality = "Lebanese", Code = "LB" },
        new CountryDto { Name = "Lesotho", Nationality = "Basotho", Code = "LS" },
        new CountryDto { Name = "Liberia", Nationality = "Liberian", Code = "LR" },
        new CountryDto { Name = "Libya", Nationality = "Libyan", Code = "LY" },
        new CountryDto { Name = "Liechtenstein", Nationality = "Liechtensteiner", Code = "LI" },
        new CountryDto { Name = "Lithuania", Nationality = "Lithuanian", Code = "LT" },
        new CountryDto { Name = "Luxembourg", Nationality = "Luxembourger", Code = "LU" },
        new CountryDto { Name = "Madagascar", Nationality = "Malagasy", Code = "MG" },
        new CountryDto { Name = "Malawi", Nationality = "Malawian", Code = "MW" },
        new CountryDto { Name = "Malaysia", Nationality = "Malaysian", Code = "MY" },
        new CountryDto { Name = "Maldives", Nationality = "Maldivian", Code = "MV" },
        new CountryDto { Name = "Mali", Nationality = "Malian", Code = "ML" },
        new CountryDto { Name = "Malta", Nationality = "Maltese", Code = "MT" },
        new CountryDto { Name = "Marshall Islands", Nationality = "Marshallese", Code = "MH" },
        new CountryDto { Name = "Mauritania", Nationality = "Mauritanian", Code = "MR" },
        new CountryDto { Name = "Mauritius", Nationality = "Mauritian", Code = "MU" },
        new CountryDto { Name = "Mexico", Nationality = "Mexican", Code = "MX" },
        new CountryDto { Name = "Micronesia", Nationality = "Micronesian", Code = "FM" },
        new CountryDto { Name = "Moldova", Nationality = "Moldovan", Code = "MD" },
        new CountryDto { Name = "Monaco", Nationality = "Monégasque", Code = "MC" },
        new CountryDto { Name = "Mongolia", Nationality = "Mongolian", Code = "MN" },
        new CountryDto { Name = "Montenegro", Nationality = "Montenegrin", Code = "ME" },
        new CountryDto { Name = "Morocco", Nationality = "Moroccan", Code = "MA" },
        new CountryDto { Name = "Mozambique", Nationality = "Mozambican", Code = "MZ" },
        new CountryDto { Name = "Myanmar (Burma)", Nationality = "Burmese", Code = "MM" },
        new CountryDto { Name = "Namibia", Nationality = "Namibian", Code = "NA" },
        new CountryDto { Name = "Nauru", Nationality = "Nauruan", Code = "NR" },
        new CountryDto { Name = "Nepal", Nationality = "Nepalese", Code = "NP" },
        new CountryDto { Name = "Netherlands", Nationality = "Dutch", Code = "NL" },
        new CountryDto { Name = "New Zealand", Nationality = "New Zealander", Code = "NZ" },
        new CountryDto { Name = "Nicaragua", Nationality = "Nicaraguan", Code = "NI" },
        new CountryDto { Name = "Niger", Nationality = "Nigerien", Code = "NE" },
        new CountryDto { Name = "Nigeria", Nationality = "Nigerian", Code = "NG" },
        new CountryDto { Name = "North Macedonia", Nationality = "Macedonian", Code = "MK" },
        new CountryDto { Name = "Norway", Nationality = "Norwegian", Code = "NO" },
        new CountryDto { Name = "Oman", Nationality = "Omani", Code = "OM" },
        new CountryDto { Name = "Pakistan", Nationality = "Pakistani", Code = "PK" },
        new CountryDto { Name = "Palau", Nationality = "Palauan", Code = "PW" },
        new CountryDto { Name = "Panama", Nationality = "Panamanian", Code = "PA" },
        new CountryDto { Name = "Papua New Guinea", Nationality = "Papua New Guinean", Code = "PG" },
        new CountryDto { Name = "Paraguay", Nationality = "Paraguayan", Code = "PY" },
        new CountryDto { Name = "Peru", Nationality = "Peruvian", Code = "PE" },
        new CountryDto { Name = "Philippines", Nationality = "Filipino", Code = "PH" },
        new CountryDto { Name = "Poland", Nationality = "Polish", Code = "PL" },
        new CountryDto { Name = "Portugal", Nationality = "Portuguese", Code = "PT" },
        new CountryDto { Name = "Qatar", Nationality = "Qatari", Code = "QA" },
        new CountryDto { Name = "Romania", Nationality = "Romanian", Code = "RO" },
        new CountryDto { Name = "Russia", Nationality = "Russian", Code = "RU" },
        new CountryDto { Name = "Rwanda", Nationality = "Rwandan", Code = "RW" },
        new CountryDto { Name = "Saint Kitts and Nevis", Nationality = "Kittitian or Nevisian", Code = "KN" },
        new CountryDto { Name = "Saint Lucia", Nationality = "Saint Lucian", Code = "LC" },
        new CountryDto { Name = "Saint Vincent and the Grenadines", Nationality = "Vincentian", Code = "VC" },
        new CountryDto { Name = "Samoa", Nationality = "Samoan", Code = "WS" },
        new CountryDto { Name = "San Marino", Nationality = "Sammarinese", Code = "SM" },
        new CountryDto { Name = "Sao Tome and Principe", Nationality = "São Toméan", Code = "ST" },
        new CountryDto { Name = "Saudi Arabia", Nationality = "Saudi", Code = "SA" },
        new CountryDto { Name = "Senegal", Nationality = "Senegalese", Code = "SN" },
        new CountryDto { Name = "Serbia", Nationality = "Serbian", Code = "RS" },
        new CountryDto { Name = "Seychelles", Nationality = "Seychellois", Code = "SC" },
        new CountryDto { Name = "Sierra Leone", Nationality = "Sierra Leonean", Code = "SL" },
        new CountryDto { Name = "Singapore", Nationality = "Singaporean", Code = "SG" },
        new CountryDto { Name = "Slovakia", Nationality = "Slovak", Code = "SK" },
        new CountryDto { Name = "Slovenia", Nationality = "Slovenian", Code = "SI" },
        new CountryDto { Name = "Solomon Islands", Nationality = "Solomon Islander", Code = "SB" },
        new CountryDto { Name = "Somalia", Nationality = "Somali", Code = "SO" },
        new CountryDto { Name = "South Africa", Nationality = "South African", Code = "ZA" },
        new CountryDto { Name = "South Sudan", Nationality = "South Sudanese", Code = "SS" },
        new CountryDto { Name = "Spain", Nationality = "Spanish", Code = "ES" },
        new CountryDto { Name = "Sri Lanka", Nationality = "Sri Lankan", Code = "LK" },
        new CountryDto { Name = "Sudan", Nationality = "Sudanese", Code = "SD" },
        new CountryDto { Name = "Suriname", Nationality = "Surinamese", Code = "SR" },
        new CountryDto { Name = "Sweden", Nationality = "Swedish", Code = "SE" },
        new CountryDto { Name = "Switzerland", Nationality = "Swiss", Code = "CH" },
        new CountryDto { Name = "Syria", Nationality = "Syrian", Code = "SY" },
        new CountryDto { Name = "Taiwan", Nationality = "Taiwanese", Code = "TW" },
        new CountryDto { Name = "Tajikistan", Nationality = "Tajikistani", Code = "TJ" },
        new CountryDto { Name = "Tanzania", Nationality = "Tanzanian", Code = "TZ" },
        new CountryDto { Name = "Thailand", Nationality = "Thai", Code = "TH" },
        new CountryDto { Name = "Togo", Nationality = "Togolese", Code = "TG" },
        new CountryDto { Name = "Tonga", Nationality = "Tongan", Code = "TO" },
        new CountryDto { Name = "Trinidad and Tobago", Nationality = "Trinidadian/Tobagonian", Code = "TT" },
        new CountryDto { Name = "Tunisia", Nationality = "Tunisian", Code = "TN" },
        new CountryDto { Name = "Turkey", Nationality = "Turkish", Code = "TR" },
        new CountryDto { Name = "Turkmenistan", Nationality = "Turkmen", Code = "TM" },
        new CountryDto { Name = "Tuvalu", Nationality = "Tuvaluan", Code = "TV" },
        new CountryDto { Name = "Uganda", Nationality = "Ugandan", Code = "UG" },
        new CountryDto { Name = "Ukraine", Nationality = "Ukrainian", Code = "UA" },
        new CountryDto { Name = "United Arab Emirates", Nationality = "Emirati", Code = "AE" },
        new CountryDto { Name = "United Kingdom", Nationality = "British", Code = "GB" },
        new CountryDto { Name = "United States", Nationality = "American", Code = "US" },
        new CountryDto { Name = "Uruguay", Nationality = "Uruguayan", Code = "UY" },
        new CountryDto { Name = "Uzbekistan", Nationality = "Uzbek", Code = "UZ" },
        new CountryDto { Name = "Vanuatu", Nationality = "Ni-Vanuatu", Code = "VU" },
        new CountryDto { Name = "Vatican City", Nationality = "Vatican", Code = "VA" },
        new CountryDto { Name = "Venezuela", Nationality = "Venezuelan", Code = "VE" },
        new CountryDto { Name = "Vietnam", Nationality = "Vietnamese", Code = "VN" },
        new CountryDto { Name = "Yemen", Nationality = "Yemeni", Code = "YE" },
        new CountryDto { Name = "Zambia", Nationality = "Zambian", Code = "ZM" },
        new CountryDto { Name = "Zimbabwe", Nationality = "Zimbabwean", Code = "ZW" }
    ];

    public static IEnumerable<CountryDto> GetAllCountries()
    {
        return Countries;
    }
}